source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Lineup' do
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Parse'
  pod 'ParseUI'
  pod 'ParseFacebookUtilsV4'
  pod 'AFNetworking'
  pod 'FoldingCell'

end
